# Generated by Django 4.0.4 on 2022-05-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Category Image', null=True, upload_to='')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product Name', max_length=255)),
                ('product_type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], max_length=255)),
                ('visible', models.BooleanField(default=True, help_text='Visible on Storefront')),
                ('description', models.TextField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('categories', models.ManyToManyField(db_table='product_categories', to='product.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('% Discount', 'percentage'), ('Fixed Amount', 'fixed')], max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_discount',
            },
        ),
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_price', models.FloatField()),
                ('free_shipping', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_shipping',
            },
        ),
        migrations.CreateModel(
            name='ProductSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_seo',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratting', models.IntegerField()),
                ('review', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductPurchasable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qt', models.FloatField(blank=True, help_text='Minimum Purchase Quantity', null=True)),
                ('max_qt', models.FloatField(blank=True, help_text='Maximum Purchase Quantity', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_purchasable',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.FloatField()),
                ('cost', models.FloatField(default=0)),
                ('msrp', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_price',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('thumbnail', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='ProductIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.SlugField()),
                ('mpn', models.CharField(blank=True, help_text='Manufacturer Part Number (MPN)', max_length=255, null=True)),
                ('upc', models.CharField(blank=True, help_text='Product UPC/EAN', max_length=255, null=True)),
                ('gtin', models.CharField(blank=True, help_text='Global Trade Item Number', max_length=255, null=True)),
                ('bpn', models.CharField(blank=True, help_text='Bin Picking Number (BPN)', max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_identifier',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(default=2, help_text='Min Quantity')),
                ('discount_unit', models.FloatField(default=0, help_text='Discount Unit By Discount Type Choice')),
                ('discount_price', models.FloatField(default=0, help_text='Discount Price')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productdiscount')),
            ],
            options={
                'db_table': 'product_discount_prices',
            },
        ),
    ]
